### ISSUE TITLE
Making code changes too?

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [nngogol/PySimpleGUIDocGen#33]
I just noticed that the PySimpleGUI.py file I was able to check in had a LOT of the import statements removed.   I looked through your db folder and your PySimpleGUIlib.py file also had these removed.

What I think I did was take your zipped up db folder and I copied and pasted your PySimpleGUI.py file over the top of mine, thinking that the changes you are making are to DOC STRINGS and only doc strings.

Are you "cleaning up code" too?   As in deleting things?

My version 2.7 imports for tkinter for example shrunk from this:
```
    import Tkinter as tk
    import tkFileDialog
    import ttk
    import tkColorChooser
    import tkFont
    import ScrolledText
```

to this:
```
    import Tkinter as tk
    import ttk
```

I'm happy to have conversations about areas of the code you believe could use improving.  But I wasn't expecting you to make these level of changes.  It has me concerned that I'm not watching close enough the changes.  I don't WANT to have to watch closely every change that you send me.

If you really feel strongly some changes need to be made, add # TODO to the code where you think the changes need to be and let me decide.  Or do a pull request for those specific ones that are "cleanup".  I just got off guard is all.  I shouldn't have done a copy and paste is what I've learned learned.

**Comment by nngogol** [comment]
I didn't touch logic, that for sure. Because, you know - `you never know what what can happen if you touch a electric board with wet hands` (like PackFormIntoFrame() func - it's just **pink magic**).

So, it's not me.

----

-> I think, that your `py3>py2 converted` has improved.
-> Maybe you did some changes.

----

My thing - modify something, that is *not logic*.
I'm a veterinarian, that care about `__doc__`'s

**Comment by MikeTheWatchGuy** [comment]
Lol.... You're awesome to work with!
